apiVersion: v1
kind: Secret
metadata:
  name: mynodeapp-secret                  # Name of the Secret
type: Opaque                              # Type of the Secret
data:
  password: abcd1234secretvalue==         # Base64 encoded value of 'abcd1234secretvalue'
  # API_KEY: apikeysecretvalue123           # Secret data encoded in base64 format